name = "Demo Extension"
namespace = "demo"
description = "Demonstrates the structure of an extension."
author = "Raiden H"
version = "1.1.0"

[[assets]]
    name = "Forest"
    description = "Forest scene"
    category = "Backgrounds"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/backgrounds/forest.png"
        layer = 0
        x = 0
        y = 0

[[assets]]
    name = "Space"
    description = "Spaaaaaaaace"
    category = "Backgrounds"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/backgrounds/space.png"
        layer = 0
        x = 0
        y = 0

[[assets]]
    name = "Stick Figure"
    description = "Simple stick figure drawing"
    category = "Bases"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/bases/stick_figure.png"
        layer = 2
        x = 387
        y = 86
        
[[assets]]
    name = "Pants"
    category = "Bottoms"
    type = "static"
    colorMode = "set"
    colorOptions = ["#FF0000", "#00FF00", "#0000FF"]
    
    [[assets.resources]]
        path = "/resources/bottoms/pants.png"
        layer = 4
        x = 450
        y = 550
        
[[assets]]
    name = "Skirt"
    category = "Bottoms"
    type = "static"
    colorMode = "picker"
    
    [[assets.resources]]
        path = "/resources/bottoms/skirt.png"
        layer = 4
        x = 397
        y = 556
        
[[assets]]
    name = "Shirt"
    category = "Tops"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/tops/shirt.png"
        layer = 5
        x = 452
        y = 388
        
[[assets]]
    name = "Dress"
    category = "Tops"
    type = "static"
    colorMode = "set"
    colorOptions = ["#f781ad", "#ab32d1", "#998496"]
    
    [[assets.resources]]
        path = "/resources/tops/dress.png"
        layer = 5
        x = 443
        y = 390

[[assets]]
    name = "Angry"
    category = "Faces"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/faces/angry.png"
        layer = 3
        x = 477
        y = 172
        
[[assets]]
    name = ":3"
    category = "Faces"
    type = "static"
    colorMode = "set"
    
    [[assets.resources]]
        path = "/resources/faces/colon_three.png"
        layer = 3
        x = 473
        y = 181
        
[[assets]]
    name = "Smile"
    category = "Faces"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/faces/smile.png"
        layer = 3
        x = 475
        y = 179

[[assets]]
    name = "Astronaut Helmet"
    description = "I'M IN SPAAAAAAACE"
    category = "Hats"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/hats/astronaut_helmet.png"
        layer = 6
        x = 378
        y = 74
        
[[assets]]
    name = "Double Top Hat"
    description = "Reginald!?!?"
    category = "Hats"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/hats/double_top_hat.png"
        layer = 6
        x = 363
        y = 0
        
[[assets]]
    name = "Top Hat"
    category = "Hats"
    type = "static"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/hats/top_hat.png"
        layer = 6
        x = 374
        y = 11
      
[[assets]]
    name = "Pixel Hat"
    category = "Hats"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/hats/pixel_hat.png"
        layer = 6
        scale = 22
        x = 469
        y = 43
      
[[assets]]
    name = "Mohawk"
    category = "Hats"
    type = "movable"
    colorMode = "picker"
    
    [[assets.resources]]
        path = "/resources/hats/mohawk_front.png"
        layer = 6
        x = 513
        y = 35
    [[assets.resources]]
        path = "/resources/hats/mohawk_back.png"
        layer = 1
        x = 468
        y = 35
        
[[assets]]
    name = "Gay Button"
    category = "Buttons"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/buttons/gay.png"
        layer = 6
        x = 479
        y = 443

[[assets]]
    name = "Star Button"
    category = "Buttons"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/buttons/star.png"
        layer = 6
        x = 498
        y = 414
        
[[assets]]
    name = "Hair Tie Bracelet"
    category = "Bracelets"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/bracelets/hair_tie.png"
        layer = 3
        x = 617
        y = 391
        
[[assets]]
    name = "Rainbow Bracelet"
    category = "Bracelets"
    type = "movable"
    colorMode = "static"
    
    [[assets.resources]]
        path = "/resources/bracelets/rainbow.png"
        layer = 3
        x = 403
        y = 395